config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :projects
  resources :departments do
    member do
      get :groups
    end
  end
  resources :groups
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :groups, class_name: Group.to_s
  with_options through: :groups do
    has_many :users, source: :users
    has_many :projects, source: :projects
  end
  has_one :manager, class_name: User.to_s, foreign_key: 'manage'

  def user?(user_id)
    users.where(id: user_id).present?
  end

  def manage?(user_id)
    manage == user_id
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, except: %i[new create]

  def index
    @departments = current_user.departments
    @departments = Department.all if current_user.admin?
  end

  def new
    @department = current_company.departments.build
    authorize @department
    @manages = User.all.pluck(:email, :id)
  end

  def create
    @department = current_company.departments.create(department_params)
    if @department.save
      flash[:success] = 'thanh cong'
      redirect_to departments_path
    else
      flash[:errors] = @department.errors.full_message
      render :new
    end
  end

  def show
    authorize @department
    @groups = @department.groups
  end

  def edit
    authorize @department
  end

  def update
    authorize @department
  end

  def groups
    authorize @department
    @groups = @department.groups
  end

  def destroy
    authorize @department
  end

  private

  def department_params
    params.require(:department).permit(:name, :manage)
  end

  def set_department
    @department = current_company.departments.find_by(id: params[:id])
  end
end

app/views/departments/groups.html.erb
<%if policy(@department).groups? %>
  <%= link_to 'tao moi nhom', new_group_path(department_id: @department.id), class: 'btn btn-primary' %>
<%end%>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Ten</th>
      <th scope="col">Xoa</th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <th scope="row"><%= group.id %></th>
        <td>
          <% if policy(group).show? %>
            <%= link_to group.name, group_path %>
          <% end %>
        </td>
        <td>
          <%if policy(group).destroy? %>
            <%= link_to 'delete', group_path(group.id), method: :delete, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/departments/index.html.erb
<%= link_to 'tao moi', new_department_path, class: 'btn btn-primary' %>

<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Ten</th>
      <th scope="col">Xoa</th>
    </tr>
  </thead>
  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <th scope="row"><%= department.id %></th>
        <td>
          <% if policy(department).show? %>
            <%= link_to department.name, groups_department_path(department.id) %>
          <% end %>
        </td>
        <td>
          <%if policy(department).destroy? %>
            <%= link_to 'delete', department_path(department.id), method: :delete, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/departments/new.html.erb
<%= form_for @department, url: departments_path, method: :post do |f| %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%= f.text_field :name, class: 'form-control', id: "name" %>
  </div>
  <div class="mb-3">
    <label for="manage" class="form-label">truong phong</label>
    <%= f.select :manage, options_for_select(@manages), {}, class: 'form-control', id: "manage" %>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/departments/show.html.erb
<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Ten</th>
      <th scope="col">Xoa</th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <th scope="row"><%= group.id %></th>
        <td>
          <% if policy(group).show? %>
            <%= link_to group.name, groups_department_path(@department.id) %>
          <% end %>
        </td>
        <td>
          <%if policy(group).destroy? %>
            <%= link_to 'delete', group_path(group.id), method: :delete, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>